### ISSUE TITLE
Does it supports Java17 environment

### ISSUE THREAD

**Issue by mercy1230** [tronprotocol/trident#125]
Can trident-java run on the Java17 environment ？

**Comment by endiaoekoe** [comment]
> Can trident-java run on the Java17 environment ？

hi, @mercy1230 
Currently, the JDK version that trident-java uses is 1.8, which remains compatible with java-tron.
In theory, trident-java could also be compatible in JRE environments larger than 1.8(eg: 17), since trident-java does not rely on certain incompatible features contained in the JREs higher than 1.8.
However, currently, trident-java has not been fully tested for compatibility on JREs larger than 1.8, such as  JRE 17, so it may not ensure that all features work perfectly in JRE 17.

**Comment by mercy1230** [comment]
> > Can trident-java run on the Java17 environment ？
> 
> hi, @mercy1230 Currently, the JDK version that trident-java uses is 1.8, which remains compatible with java-tron. In theory, trident-java could also be compatible in JRE environments larger than 1.8(eg: 17), since trident-java does not rely on certain incompatible features contained in the JREs higher than 1.8. However, currently, trident-java has not been fully tested for compatibility on JREs larger than 1.8, such as JRE 17, so it may not ensure that all features work perfectly in JRE 17.

Thanks (*^▽^*)
