### ISSUE TITLE
Multisign transactions

### ISSUE THREAD

**Issue by simbadMarino** [tronprotocol/trident#140]
Hello team, I could not find any docs related to performing multisign transactions using Trident. 
Would you please point me to the right docs or even a code example on how to do this on trident?

Thanks in advance!

**Comment by angrynurd** [comment]
@simbadMarino 
currently,there are code examples of multisig tx using tronweb sdk(js lib), and there are not code examples of multisi tx using trident(java lib).
if you want to  perform multisig tx using trident ,you can refer to[ this docs](https://developers.tron.network/docs/multi-signature-example-process-flow),and **make sure to replace this methods mentioned in this docs with according methods in Apiwrapper**

let me make it more clearly.in order to perform a multisi tx ,you need to invoking these APIs  in order,as below:

1. Modify Account Permission --->wallet/accountpermissionupdate
2. Query Account Permission------>wallet/getaccount
3.  construct a multi-signature tx ----->sendTrx
4. Perform the Multi-Signing---->multiSign
5. Check Transaction's Sign Weight------>getSignWeight

so,if you use trident sdk to perform multisig tx,you need to invoke the specific methods in Apiwrapper,as below:
1. Modify Account Permission --->Apiwrapper.accountPermissionUpdate
2. Query Account Permission------>Apiwrapper.getaccount
3.  construct a multi-signature tx ----->Apiwrapper.createTransaction
4. Perform the Multi-Signing---->Apiwrapper.signTransaction
5. Check Transaction's Sign Weight------>Apiwrapper.getTransactionSignWeight

you can have try.
by the way,it will be better to add the missing part in the docs of trident  about the multisig tx ;
