### ISSUE TITLE
The transfer method cannot transfer the decimal trc20（example：0.01trc20）

### ISSUE THREAD

**Issue by qq335103060** [tronprotocol/trident#6]
transfer(String destAddr, long amount,  String memo, long feeLimit) 
transfer Cannot trade decimals TRC20

**Comment by Starsakary** [comment]
Thanks. The reason for the error is code of Trc20Contact.transfer and transferFrom are hardcoded so that you can't transfer non-integer values. This will be fixed in the next version.

For now, you can construct a Function like:

```java
Function transfer = new Function("transfer",
                Arrays.asList(new Address(destAddr),
                        new Uint256(BigInteger.valueOf(amount).multiply(BigInteger.valueOf(10).pow(n)))),
                Arrays.asList(new TypeReference<Bool>() {}));
```
You may customise the value of 'n' to transfer any value.

**Comment by pvyhnal-generalbytes** [comment]
what exactly is the issue here? 
the `long amount` parameter is supposed to be in the lowest denomination of the token. You shouldn't need to (be able to) send smaller amounts, right?
For example USDT [1] has Precision: 6, so when sending 0.01 USDT the amount would be 10000
( `new BigDecimal("0.01").movePointRight(6).longValue()` and you can get the Precision value from `org.tron.trident.core.contract.Trc20Contract#decimals`)

Am I getting this right?

[1] https://tronscan.org/#/token20/TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

**Comment by pvyhnal-generalbytes** [comment]
Is the problem here when the token does not return correct decimals() value?

**Comment by pvyhnal-generalbytes** [comment]
never mind I understand now, sorry :)
