### ISSUE TITLE
TriggerSmartContract at a specific height

### ISSUE THREAD

**Issue by alecalve** [tronprotocol/trident#81]
Is it possible to execute a contract transaction against another block height than the latest?

Something similar to `eth_call`'s second argument (blockNumber/tag).

**Comment by xq-lu** [comment]
> Is it possible to execute a contract transaction against another block height than the latest?
> 
> Something similar to `eth_call`'s second argument (blockNumber/tag).

hi,alecalve
Currently,java-tron only support execute a contract transaction against latest block,you can refer to this doc:https://developers.tron.network/reference/eth_call ,which mentioned in this doc 'currently, only "latest" is available.'

In Ethereum, To send eth_call, the user can specify the block as a number/hash, “latest”, ”earliest” or “pending”. the difference is below:
If you specify a number/hexadecimal string, the client will run it against an old block state with the specific block number.
“Latest” block for the current state.
The “Earliest” block is the earliest block available. For a full node, it is usually 128 blocks from the current block.
The “Pending” block is an imaginary block that will likely be validated next. However, it is not guaranteed. Normally, the real block validated differs from the “pending” block.

The reason is Ethereum support 'state trie/world state', so the user can choose execute a contract transaction against a specific state. Currently,java-tron did not support the ‘state trie/world state’， so 'lastest' is the only option.

Fortunately, Java-Tron will support 'state trie/world state' soon. With java-tron's support for state trie, your request should be implemented soon.

**Comment by alecalve** [comment]
Thanks for the answer, when you say it will be supported "soon", how close is that? weeks? months? years?

**Comment by xq-lu** [comment]
> Thanks for the answer, when you say it will be supported "soon", how close is that? weeks? months? years?

hi,alecalve
The development process of 'state trie' feature is almost complete.You can track the latest progress of development for this feature in this branch https://github.com/tronprotocol/java-tron/commits/feature/state-trie-final .
Currently the feature is in the process of testing ,which may need some time.
By the way, please keep an eye on the latest announcements once this feature goes live.thanks.

**Comment by alecalve** [comment]
Thanks, I will keep an eye when it's out. 

When released, will it only work for new blocks, or will we be able to query data for blocks that are older than the state trie feature activation?

**Comment by xq-lu** [comment]
> Thanks, I will keep an eye when it's out.
> 
> When released, will it only work for new blocks, or will we be able to query data for blocks that are older than the state trie feature activation?

hi,alecalve
It will support query data for all the blocks since genesis block after the state trie featrue roll out.

**Comment by alecalve** [comment]
Amazing, thanks for your answers
